// 가격, 할인, 배송, 쿠폰은 실제 판매 조건이 아닌 시안용 예시 데이터입니다.
export const shop = {
  coupon: 3000,
  shipping: 4000,
  freeShipping: 50000,
  phone: "02-0000-0000",
  hours: "평일 10:00 – 17:00",
  maxDiscount: 40,
};
export const images = {
  hero: "/images/aquarium.jpg",
  beginner: "/images/beginner.jpg",
  guppy: "/images/guppy.jpg",
  betta: "/images/betta.jpg",
  tetra: "/images/tetra.jpg",
  cory: "/images/cory.jpg",
  shrimp: "/images/shrimp.jpg",
  plants: "/images/plants.jpg",
};
export const categories = [
  { name: "구피", key: "guppy", caption: "작은 꼬리, 다채로운 매력" },
  { name: "베타", key: "betta", caption: "물속을 수놓는 우아함" },
  { name: "테트라", key: "tetra", caption: "반짝이는 작은 물결" },
  { name: "코리도라스", key: "cory", caption: "바닥 위의 귀여운 친구" },
  { name: "새우", key: "shrimp", caption: "작지만 확실한 존재감" },
  { name: "수초", key: "plants", caption: "싱그러운 수중 정원" },
];
export const products = [
  {
    id: "guppy",
    name: "모스코 블루 구피",
    unit: "1마리",
    description: "깊고 선명한 블루 컬러",
    category: "열대어",
    type: "구피",
    image: images.guppy,
    price: 10000,
    discount: 40,
    badge: "초특가",
    popular: true,
  },
  {
    id: "tetra",
    name: "네온테트라",
    unit: "5마리",
    description: "무리 지어 빛나는 푸른 보석",
    category: "열대어",
    type: "테트라",
    image: images.tetra,
    price: 10000,
    discount: 30,
    badge: "입문 추천",
    popular: true,
  },
  {
    id: "betta",
    name: "코이 베타",
    unit: "1마리",
    description: "한 마리만으로 완성되는 아름다움",
    category: "열대어",
    type: "베타",
    image: images.betta,
    price: 20000,
    discount: 25,
    badge: "인기",
    popular: true,
  },
  {
    id: "shrimp",
    name: "레드 체리새우",
    unit: "10마리",
    description: "수초 사이의 사랑스러운 포인트",
    category: "열대어",
    type: "새우",
    image: images.shrimp,
    price: 15000,
    discount: 20,
    badge: "초특가",
    popular: false,
  },
  {
    id: "cory",
    name: "팬더 코리도라스",
    unit: "1마리",
    description: "순한 성격의 귀여운 바닥 친구",
    category: "열대어",
    type: "코리도라스",
    image: images.cory,
    price: 8000,
    discount: 0,
    badge: "입문 추천",
    popular: true,
  },
  {
    id: "plants",
    name: "아누비아스 나나",
    unit: "1포트",
    description: "차분한 초록빛, 쉬운 수초 생활",
    category: "수초",
    type: "수초",
    image: images.plants,
    price: 10000,
    discount: 10,
    badge: "입문 추천",
    popular: false,
  },
];
export const salePrice = (p) =>
  Math.round((p.price * (100 - p.discount)) / 100);
export const won = (value) => value.toLocaleString("ko-KR");
